# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
  DOCKER_BUILDKIT: 1
  COMPOSE_INTERACTIVE_NO_CLI: 1

jobs:
- job: Setup
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: docker buildx create --use
    displayName: 'Setup Multi Build'
  - script: docker build -o type=tar,dest=./appwrite.tar .
    displayName: 'Setup Appwrite'
  - publish: ./appwrite.tar
    artifact: Appwrite
  - script: |
        docker ps
        docker-compose logs appwrite
        docker-compose exec appwrite doctor
        docker-compose exec appwrite vars
    displayName: 'Show Status'

- job: Test
  dependsOn: Setup
  pool:
    vmImage: 'ubuntu-latest'
  strategy:
    maxParallel: 2
    matrix: 
      E2E:
        Path: /usr/src/code/tests/e2e
      Unit:
        Path: /usr/src/code/tests/unit
  steps:
    - download: current
      artifact: Appwrite
    - script: |
        docker load --input $(System.DefaultWorkingDirectory)/tmp/appwrite.tar
        docker-compose exec appwrite $(Path)
      displayName: 'Run Tests'