# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  DOCKER_BUILDKIT: 1
  COMPOSE_INTERACTIVE_NO_CLI: 1

strategy:
  maxParallel: 5
  matrix: 
    E2E:
      Path: /usr/src/code/tests/e2e
    Unit:
      Path: /usr/src/code/tests/unit

steps:
- script: docker buildx create --use
  displayName: 'Setup Multi Build'

- script: docker build -o type=docker,dest=$(System.DefaultWorkingDirectory)/tmp/appwrite.tar
  displayName: 'Setup Appwrite'
- publish: $(System.DefaultWorkingDirectory)/tmp/appwrite.tar
  artifact: Appwrite

- script: |
    docker ps
    docker-compose logs appwrite
    docker-compose exec appwrite doctor
    docker-compose exec appwrite vars
  displayName: 'Show Status'

- script: |
    docker-compose exec appwrite $(Path)
  displayName: 'Run Tests'
